"""init

Revision ID: 08baf8177400
Revises: dd33cb03d01f
Create Date: 2023-05-04 22:37:17.346262

"""

# revision identifiers, used by Alembic.
revision = '08baf8177400'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
