"""init

Revision ID: 3ce6807134b6
Revises: c86f670bba4e
Create Date: 2023-05-05 00:14:22.194829

"""

# revision identifiers, used by Alembic.
revision = '3ce6807134b6'
down_revision = 'c86f670bba4e'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
