"""init

Revision ID: 639145f86fd4
Revises: de753224ff14
Create Date: 2023-05-05 00:26:10.878136

"""

# revision identifiers, used by Alembic.
revision = '639145f86fd4'
down_revision = 'de753224ff14'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
