"""init

Revision ID: 86d1fc8e4f28
Revises: 08baf8177400
Create Date: 2023-05-04 22:51:06.843751

"""

# revision identifiers, used by Alembic.
revision = '86d1fc8e4f28'
down_revision = '08baf8177400'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
