"""init

Revision ID: 8b3ce3f376f0
Revises: 639145f86fd4
Create Date: 2023-05-05 00:26:46.938796

"""

# revision identifiers, used by Alembic.
revision = '8b3ce3f376f0'
down_revision = '639145f86fd4'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
