"""init

Revision ID: 9d6d7c73c4ff
Revises: 8b3ce3f376f0
Create Date: 2023-05-05 00:29:08.959189

"""

# revision identifiers, used by Alembic.
revision = '9d6d7c73c4ff'
down_revision = '8b3ce3f376f0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
