"""init

Revision ID: c86f670bba4e
Revises: d474639e86a8
Create Date: 2023-05-05 00:12:52.935117

"""

# revision identifiers, used by Alembic.
revision = 'c86f670bba4e'
down_revision = 'd474639e86a8'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
