"""init

Revision ID: d474639e86a8
Revises: 86d1fc8e4f28
Create Date: 2023-05-05 00:12:01.246659

"""

# revision identifiers, used by Alembic.
revision = 'd474639e86a8'
down_revision = '86d1fc8e4f28'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
